/// Keychain abstraction — injectable for testing.
///
/// In production: `RealKeychain` wraps macOS Keychain via security-framework.
/// In tests: `MockKeychain` (auto-generated by mockall) is used.
const SERVICE: &str = "mac-haze";

#[cfg_attr(test, mockall::automock)]
pub trait KeychainStore: Send + Sync + 'static {
    /// Persist steam_id, username, and api_key. Overwrites existing entries.
    fn save(&self, steam_id: u64, username: &str, api_key: &str) -> Result<(), String>;

    /// Load persisted credentials, if present.
    fn load(&self) -> Option<(u64, String, String)>;

    /// Delete all persisted credentials (used by compensate / re-onboarding).
    fn clear(&self);
}

// ─── Real macOS Keychain implementation ────────────────────────────────────

pub struct RealKeychain;

#[cfg(target_os = "macos")]
impl KeychainStore for RealKeychain {
    fn save(&self, steam_id: u64, username: &str, api_key: &str) -> Result<(), String> {
        use security_framework::passwords::set_generic_password;

        set_generic_password(SERVICE, "steam_id", steam_id.to_string().as_bytes())
            .map_err(|e| e.to_string())?;
        set_generic_password(SERVICE, "username", username.as_bytes())
            .map_err(|e| e.to_string())?;
        set_generic_password(SERVICE, "api_key", api_key.as_bytes())
            .map_err(|e| e.to_string())?;
        Ok(())
    }

    fn load(&self) -> Option<(u64, String, String)> {
        use security_framework::passwords::get_generic_password;

        let steam_id: u64 = String::from_utf8(get_generic_password(SERVICE, "steam_id").ok()?)
            .ok()?
            .parse()
            .ok()?;
        let username =
            String::from_utf8(get_generic_password(SERVICE, "username").ok()?).ok()?;
        let api_key =
            String::from_utf8(get_generic_password(SERVICE, "api_key").ok()?).ok()?;
        Some((steam_id, username, api_key))
    }

    fn clear(&self) {
        use security_framework::passwords::delete_generic_password;

        let _ = delete_generic_password(SERVICE, "steam_id");
        let _ = delete_generic_password(SERVICE, "username");
        let _ = delete_generic_password(SERVICE, "api_key");
    }
}

// Stub for non-macOS builds (CI on Linux, etc.)
#[cfg(not(target_os = "macos"))]
impl KeychainStore for RealKeychain {
    fn save(&self, _: u64, _: &str, _: &str) -> Result<(), String> {
        Ok(())
    }
    fn load(&self) -> Option<(u64, String, String)> {
        None
    }
    fn clear(&self) {}
}
